spring.datasource.url=jdbc:postgresql://localhost:5432/orienta_tech_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=orienta_tech_super_secret_key_2024
jwt.expiration=86400000

server.port=8080

spring.main.allow-circular-references=true